package timotomata.lexer;

public enum TipoToken {
    SENSOR, UMBRAL, SI, ENTONCES, ESTADO, ABS,
    ID, NUMERO, ESTADO_SISTEMA,
    MAYOR, MENOR, IGUAL_IGUAL, MAYOR_IGUAL, MENOR_IGUAL, DIFERENTE,
    MAS, MENOS, POR, DIV,
    ASIGNACION, PUNTO_COMA, PAREN_IZQ, PAREN_DER,
    EOF
}
